/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "auth.h"
#include <iostream>
#include <sstream>
#include <fstream>

using namespace std;

void
auth_1(char *host, char *client_file)
{
	CLIENT *clnt;
	int  *result_1;
	intermediar  afisare_1_arg;


#ifndef	DEBUG
	clnt = clnt_create (host, AUTH, A1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	ifstream in(client_file);
	string line;
	while (getline(in, line)) {
		stringstream ss(line);
		string id, action, res;
		getline(ss, id, ','), getline(ss, action, ','), getline(ss, res, ',');
		cout << id << action << res << '\n';
	}

	result_1 = afisare_1(&afisare_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *client_file;

	if (argc < 3) {
		printf ("usage: %s server_host client_file\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	client_file = argv[2];
	auth_1 (host, client_file);
exit (0);
}
