/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "auth.h"
#include <iostream>
#include "auth_server_shared.h"

using namespace std;

char **
afisare_1_svc(request *argp, struct svc_req *rqstp)
{
	static char * result;

	return &result;
}
