/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "auth.h"


void
auth_1(char *host)
{
	CLIENT *clnt;
	response  *result_1;
	request  afisare_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, AUTH, A1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = afisare_1(&afisare_1_arg, clnt);
	if (result_1 == (response *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("result: %s\n", result_1->msg);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	auth_1 (host);
exit (0);
}
