/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUTH_H_RPCGEN
#define _AUTH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct request {
	char *id;
	char *action;
	char *res;
};
typedef struct request request;

#define AUTH 0x23451111
#define A1 1

#if defined(__STDC__) || defined(__cplusplus)
#define afisare 1
extern  char ** afisare_1(request *, CLIENT *);
extern  char ** afisare_1_svc(request *, struct svc_req *);
extern int auth_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define afisare 1
extern  char ** afisare_1();
extern  char ** afisare_1_svc();
extern int auth_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_request (XDR *, request*);

#else /* K&R C */
extern bool_t xdr_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AUTH_H_RPCGEN */
