/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUTH_H_RPCGEN
#define _AUTH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct request {
	char *id;
	char *action;
	char *res;
};
typedef struct request request;

struct answer {
	char *resp;
};
typedef struct answer answer;

#define AUTH 1
#define A1 1

#if defined(__STDC__) || defined(__cplusplus)
#define afisare 1
extern  int * afisare_1(char **, CLIENT *);
extern  int * afisare_1_svc(char **, struct svc_req *);
extern int auth_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define afisare 1
extern  int * afisare_1();
extern  int * afisare_1_svc();
extern int auth_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_request (XDR *, request*);
extern  bool_t xdr_answer (XDR *, answer*);

#else /* K&R C */
extern bool_t xdr_request ();
extern bool_t xdr_answer ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AUTH_H_RPCGEN */
