/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "auth.h"
#include <iostream>

using namespace std;

char **
afisare_1_svc(request *argp, struct svc_req *rqstp)
{
	static char * result;

	cout << argp->action << argp->id << argp->res <<'\n';

	/*
	 * insert server code here
	 */



	return &result;
}
