/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "auth.h"
#include <stdio.h>
#include <stdlib.h>
#include <unordered_map>
using namespace std;

void
auth_1(char *host, char *op_file)
{
	CLIENT *clnt;
	int  *result_1;
	intermediar  afisare_1_arg;

	FILE *file;
	char line[256];
	file = fopen(op_file, "r");

	char id[20], action[20], resource[20]; 
	while (fgets(line, sizeof(line), file)) {
		int n = sscanf(line, "%19[^,],%19[^,],%19s", id, action, resource);
		if (n == 3){
			printf("%s %s %s\n", id, action, resource);
		}
	}


#ifndef	DEBUG
	clnt = clnt_create (host, AUTH, A1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = afisare_1(&afisare_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *op_file;

	if (argc != 3) {
		printf ("usage: %s server_host operation_file\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	op_file = argv[2];
	auth_1 (host, op_file);
	exit (0);
}
